name: update depotdownloader
on:
  # schedule:
  #   # Run daily at 00:00 UTC
  #   - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install -r update/requirements.txt
      - run: python update/update.py > depotdownloader_version.bzl
      - uses: peter-evans/create-pull-request@v5
        with:
          branch: update-release-branch
          title: 'Update Linux Release Info'
          labels: 'automated'
          commit-message: 'Update Linux release info'
          delete-branch: true
