name: update-example
on:
  schedule:
    - cron: "0 0 * * *" # daily at midnight UTC
  workflow_dispatch:

jobs:
  update-example:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: "${{ vars.RENOVATE_APP_ID }}"
          private-key: "${{ secrets.RENOVATE_APP_PRIVATE_KEY }}"
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - run: ./examples/update-steamapps.sh

      - run: bazel mod deps

      - name: Check for changes
        id: git-check
        run: |
          git add .
          # if there are staged changes, set an output variable
          if ! git diff --cached --quiet; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit & push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git commit -m "Update example to build $(grep -oP 'BUILD_\w+\s*=\s*"\K\d+' steamapps.bzl)"
          git push
